DELETE FROM Department;
INSERT INTO Department VALUES (1, 'Computer Science', 'COMP');
INSERT INTO Department VALUES (2, 'Engineering', 'ENGR');
INSERT INTO Department VALUES (3, 'Mathematics', 'MATH');
INSERT INTO Department VALUES (4, 'Electrical Engineering', 'EENG');
INSERT INTO Department VALUES (5, 'Bible New Testament', 'BNEW');
INSERT INTO Department VALUES (6, 'Bible Old Testament', 'BOLD');
INSERT INTO Department VALUES (7, 'English', 'ENG');
INSERT INTO Department VALUES (8, 'Communication', 'COMM');
INSERT INTO Department VALUES (9, 'Economics', 'ECON');
INSERT INTO Department VALUES (10, 'Sociology', 'SOC');
INSERT INTO Department VALUES (11, 'Kinesiology', 'KINS');
INSERT INTO Department VALUES (12, 'Psychology', 'PSY');
INSERT INTO Department VALUES (13, 'Biology', 'BIOL');
INSERT INTO Department VALUES (14, 'Physical Science', 'PHS');
INSERT INTO Department VALUES (15, 'Art', 'ART');
INSERT INTO Department VALUES (16, 'Music', 'MUS');
INSERT INTO Department VALUES (17, 'Theatre', 'THEA');
INSERT INTO Department VALUES (18, 'History', 'HIST');
INSERT INTO Department VALUES (19, 'Political Science', 'POLS');
INSERT INTO Department VALUES (20, 'Anthropology', 'ANTH');
INSERT INTO Department VALUES (21, 'Bible History', 'BHIS');
INSERT INTO Department VALUES (22, 'Bible Missions', 'BMIS');
INSERT INTO Department VALUES (23, 'Communication Sciences and Disorders', 'CSD');
INSERT INTO Department VALUES (24, 'Finance', 'FIN');
INSERT INTO Department VALUES (25, 'Global Economic Development', 'GEDV');
INSERT INTO Department VALUES (26, 'Geography', 'GEOG');
INSERT INTO Department VALUES (27, 'Honors', 'HNRS');
INSERT INTO Department VALUES (28, 'Humanities', 'HUM');
INSERT INTO Department VALUES (29, 'International Business', 'IB');
INSERT INTO Department VALUES (30, 'International Study Abroad', 'INST');
INSERT INTO Department VALUES (31, 'Information Systems', 'IS');
INSERT INTO Department VALUES (32, 'Modern Greek', 'MGRK');
INSERT INTO Department VALUES (33, 'Preprofessional Health Science', 'PPHS');
INSERT INTO Department VALUES (34, 'Nursing', 'NURS');
INSERT INTO Department VALUES (35, 'Social Sciences', 'SOCS');
INSERT INTO Department VALUES (36, 'Social Work', 'SWK');
INSERT INTO Department VALUES (37, 'Chemistry', 'CHEM');
INSERT INTO Department VALUES (38, 'Bible Doctrine', 'BDOC');